apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nginx-deploy-rq
  labels:
    app: nginx
  namespace: dev-team
spec:
  replicas: 10       # 20 replicas will not be scheduled, because there is limit of 10 pods in this namespace
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx  
          image: nginx 
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "50m"
              memory: "50Mi"
            limits:
              cpu: "100m"
              memory: "100Mi"