---
apiVersion: apps/v1
kind: Deployment #Controller
metadata:
  name: httpd-deploy
  labels:
    app: httpd
spec: 
  replicas: 10
  selector:
    matchLabels:
      app: httpd  
  template:
    metadata:
      name: simple-pod
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd
          image: httpd
          ports:
            - containerPort: 80
---
apiVersion: v1 
kind: Service
metadata:
  name: httpd-lb-svc 
  labels:
    app: httpd 
spec:
  type: LoadBalancer
  selector:
    app: httpd 
  ports:
  - port: 80                #cloud loadbalancer will be created
    targetPort: 80